### ISSUE TITLE
v1.3.0: Optimize command does not work

### ISSUE THREAD

**Issue by lutdev** [appstract/laravel-opcache#68]
**Laravel version:** 5.1
**PHP version:** 5.6

Run command `php artisan opcache:optimize`.

Log:
```
exception 'InvalidArgumentException' with message 'The "<PROJECT_PATH>/routes" directory does not exist.' in /usr/share/nginx/api/vendor/symfony/finder/Finder.php:636
Stack trace:
#0 /usr/share/nginx/api/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(302): Symfony\Component\Finder\Finder->in(Array)
#1 /usr/share/nginx/api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(216): Illuminate\Filesystem\Filesystem->allFiles(Array)
#2 /usr/share/nginx/api/vendor/appstract/laravel-opcache/src/OpcacheClass.php(78): Illuminate\Support\Facades\Facade::__callStatic('allFiles', Array)
#3 /usr/share/nginx/api/vendor/appstract/laravel-opcache/src/OpcacheClass.php(78): Illuminate\Support\Facades\File::allFiles(Array)
#4 /usr/share/nginx/api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(213): Appstract\Opcache\OpcacheClass->optimize()
#5 /usr/share/nginx/api/vendor/appstract/laravel-opcache/src/Http/Controllers/OpcacheController.php(50): Illuminate\Support\Facades\Facade::__callStatic('optimize', Array)
#6 /usr/share/nginx/api/vendor/appstract/laravel-opcache/src/Http/Controllers/OpcacheController.php(50): Appstract\Opcache\OpcacheFacade::optimize()
#7 [internal function]: Appstract\Opcache\Http\Controllers\OpcacheController->optimize()
```

The problem in the config file in the `directories`. File `routes.php` exists in the `app/Http` directory and array should be
```
'directories' => [
    base_path('app'),
    base_path('bootstrap'),
    base_path('public'),
    base_path('resources/lang'),
    app_path('Http/routes'),
    base_path('storage/framework/views'),
    base_path('vendor/appstract'),
    base_path('vendor/composer'),
    base_path('vendor/laravel/framework'),
]
```

**Comment by ovanschie** [comment]
Laravel 5.1 is not supported anymore. If you use the old route structure, you can change the config locally in your project.
