### ISSUE TITLE
Guzzle ServerException

### ISSUE THREAD

**Issue by pe3udent** [appstract/laravel-opcache#9]
Hi,

Laravel 5.2.45, Guzzle 6.2.2

`php artisan opcache:clear` output:

```
 [GuzzleHttp\Exception\ServerException]
  Server error: `GET https://.../opcache-api/clear` resulted in a `500 Internal Server Error` response:
  <!DOCTYPE html>
  <html>
      <head>
          <meta name="robots" content="noindex,nofollow" />
          <style>
               (truncated...)
```

Full stack trace:
```
in /home/.../vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /home/.../vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/.../vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/.../vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/.../vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/.../vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /home/.../vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /home/.../vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /home/.../vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /home/.../vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/.../vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Promise\Promise->wait()
#10 /home/.../vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('get', 'https://...', Array)
#11 /home/.../vendor/appstract/laravel-opcache/src/Commands/Clear.php(32): GuzzleHttp\Client->__call('get', Array)
#12 [internal function]: Appstract\Opcache\Commands\Clear->handle()
#13 /home/.../bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array)
#14 /home/.../vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#15 /home/.../vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/.../vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Cons
#17 /home/.../vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/.../vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Appstract\Opcache\Commands\Clear), Object(Symfony\Component\Console\Input\ArgvInput), Obj
#19 /home/.../vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutpu
#20 /home/.../vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Componen
#21 /home/.../artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 {main}..
```

Could you help me please?

**Comment by pe3udent** [comment]
If open in browser `https://some.dev/opcache-api/clear`
another error:
```
ReflectionException in Container.php line 734:
Class bindings does not exist
```

**Comment by ovanschie** [comment]
Please update to the latest version, and try again.

**Comment by pe3udent** [comment]
Awesome! Thanks!
